docs/overview/concepts/model.rst
I have:
- updated descriptions
Fixes #
=> updated description

docs/conf.py
- better nav bar
- fills page better 
- auto light/dark mode
I have:
-
Fixes #
=> switch to furo theme

docs/reference/knownissues.rst, docs/reference/troubleshooting.rst
I have:
- remove duplicate page
- move info to exisitng page
Fixes #
=> fix troubleshooting page

.github/workflows/runcliwhl.yml, docs/quickstart/jobs.rst, examples/iris/iris-job.yml, examples/train/basic-command-job/command_job.yml, examples/train/basic-command-job/hello_python_job.yml, examples/train/basic-command-job/pip_freeze_job.yml, examples/train/fastai/mnist-resnet18/fastai_mnist_job.yml, examples/train/fastai/pets-resnet34/fastai_pets_job.yml, examples/train/mldotnet/mlnetjob.yml, examples/train/tensorflow/mnist-distributed/tf_distr_job.yml, examples/train/tensorflow/mnist-horovod/tf_horovod_job.yml, examples/train/tensorflow/mnist/tf_mnist_job.yml
=> Remove name from examples and update CLI version

.github/workflows/sphinx-docs-pr.yml, docs/README.md, docs/azhelpgen/__init__.py, docs/azhelpgen/azhelpgen.py, docs/cligroup/__init__.py, docs/cligroup/cligroup.py, docs/conf.py, docs/generate.py, docs/index.rst, docs/reference/azure-ml.rst, docs/requirements.txt
=> get the first version work

.github/workflows/runcliwhl.yml, .github/workflows/sphinx-docs.yml
=> Update the wheel to 0.0.15

.github/workflows/runcliwhl.yml
=> Use CLI 0.19

examples/deploy/sklearn/simplemodel.yml
=> Fix model sample

.github/ISSUE_TEMPLATE/cli_issue.md, .github/ISSUE_TEMPLATE/repo_issue.md, CONTRIBUTING.md, README.md, SECURITY.md
I have:
- add SECURITY.md
- add CONTRIBUTING.md
- add two GH issue templates 
- fill out README.md a little better; could still use improvments
Fixes #151 maybe others
=> create github issue templates; SECURITY.md; CONTRIBUTING.md

docs/slides/index.html
=> final touches

.github/workflows/endpoints-e2e.yml
I have:
- [ X] read and followed the contributing guidelines
- parameterizing cli version in github action
Fixes #
=> parameterizing cli version in github action

.github/workflows/endpoints-e2e.yml
I have:
- [X ] read and followed the contributing guidelines
-
Fixes #
=> fixing the endpoint GH action variable

.github/workflows/endpoints-e2e.yml, examples/endpoints/online/managed/canary-declarative-flow/1-create-endpoint-with-blue.yaml, examples/endpoints/online/managed/canary-declarative-flow/2-scale-blue.yaml, examples/endpoints/online/managed/canary-declarative-flow/3-create-green.yaml, examples/endpoints/online/managed/canary-declarative-flow/4-flight-green.yaml, examples/endpoints/online/managed/canary-declarative-flow/5-full-green.yaml, examples/endpoints/online/managed/canary-declarative-flow/6-delete-blue.yaml, examples/endpoints/online/managed/canary-imperative-flow/2-create-blue.yaml, examples/endpoints/online/managed/canary-imperative-flow/3-create-green.yaml, examples/endpoints/online/managed/simple-flow/1-create-endpoint-with-blue.yaml
I have:
- [ X] read and followed the contributing guidelines
- env name in endpoints & fix syntax error in endpoint GH action
Fixes #
=> change env name in online endpoints

docs/overview/concepts/endpoints/batch-endpoint/batch-endpoint.rst
=> Update batch endpoint

.github/workflows/runcliwhl.yml, .github/workflows/sphinx-docs-pr.yml, .github/workflows/sphinx-docs.yml, docs/overview/concepts/endpoints/batch-endpoint/batch-endpoint.rst
=> Update cli version

docs/quickstart/distributed-training.rst
=> reword size limitation

docs/overview/concepts/endpoints/online-endpoint/scenarios/declarative-flow.rst, docs/overview/concepts/endpoints/online-endpoint/scenarios/simple-deploy-flow.rst, docs/overview/setup.rst
I have:
- [X ] read and followed the contributing guidelines
- Self registration works on for MS tenant - updated the docs
Fixes #
- spelling mistake in endpoint update docs
=> update docs about self registration

docs/overview/concepts/endpoints/online-endpoint/scenarios/simple-deploy-flow.rst
I have:
- [X ] read and followed the contributing guidelines
-
Fixes #
- update endpoint docs
=> update endpoint docs

docs/overview/concepts/environment.rst, examples/deploy/sklearn/environment/conda.yml, examples/endpoints/batch/mnist/environment/conda.yml
=> Update samples with required python in conda specification

docs/overview/concepts/compute.rst, docs/overview/concepts/data.rst
Formatting is a little off.
I have:
-
Fixes #
=> fix: Formatting issue with data.rst

docs/overview/concepts/endpoints/online-endpoint/online-endpoint.rst, docs/overview/concepts/endpoints/online-endpoint/scenarios/simple-deploy-flow.rst
I have:
- No content changes. Markdown formatting fixes to make lists present not as one paragraph. Typos.
Fixes #
=> Minor formatting fixes/spelling for readability.

docs/quickstart/distributed-training.rst, examples/dask/dask-job.yaml, examples/dask/src/batch.py, examples/dask/src/startDask.py
=> enable jupyter for debugging

.github/workflows/runcliwhl.yml, docs/overview/concepts/endpoints/batch-endpoint/batch-endpoint.rst
=> Update batch endpoint invoke

docs/overview/concepts/data.rst, docs/overview/concepts/datastore.rst
I have:
- Data documentation
Fixes #
=> Updates to manage data docs

docs/overview/concepts/endpoints/batch-endpoint/batch-endpoint.rst, docs/overview/concepts/environment.rst, docs/overview/installation.rst, docs/quickstart/jobs.rst
I have:
- Wording fixes mostly. Update to what gets shown when typing 'az ml'
Fixes # n/a
=> Minor doc changes for readability mostly.

docs/overview/concepts/environment.rst
I have:
- Update Environment concept doc
Fixes #
=> Updates to Environment documentation

examples/endpoints/batch/mnist/code/digit_identification.py
=> Update batch scoring script

docs/overview/concepts.rst, docs/overview/concepts/model.rst, docs/overview/concepts/sweepjob.rst, docs/quickstart/jobs.rst, examples/environments/conda_env.yml, examples/train/basic-command-job/hello_python_job.yml
I have:
- Update model concept doc
- Update job concept doc
Fixes #
=> Update job and model docs

examples/endpoints/batch/add-deployment.yml, examples/endpoints/batch/create-batch-endpoint.yml
=> Update batch endpoint output

.github/workflows/runcliwhl.yml, docs/quickstart/endpoints.rst, docs/slides/index.html, examples/deploy/sklearn/basicaksendpoint.yml, examples/endpoints/batch/add-deployment.yml, examples/endpoints/batch/create-batch-endpoint.yml, examples/endpoints/online/managed/canary-declarative-flow/1-create-endpoint-with-blue.yaml, examples/endpoints/online/managed/canary-declarative-flow/2-scale-blue.yaml, examples/endpoints/online/managed/canary-declarative-flow/3-create-green.yaml, examples/endpoints/online/managed/canary-declarative-flow/4-flight-green.yaml, examples/endpoints/online/managed/canary-declarative-flow/5-full-green.yaml, examples/endpoints/online/managed/canary-declarative-flow/6-delete-blue.yaml, examples/endpoints/online/managed/simple-flow/1-create-endpoint-with-blue.yaml
=> update examples for endpoint

docs/overview/installation.rst
=> instructions on installing the Python core SDK

README.md
=> update CLI install
